name: Testing

on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        run: cargo test --release --all-features

      - name: Multi-threaded tests
        run: cargo test --test integration -- multi_thread

      - name: Multi-threaded integration tests
        run: cargo test --all-features --test integration -- multi_thread

      - name: Single-threaded test
        run: cargo test --test integration -- single_thread
      
      - name: Single-threaded integration tests
        run: cargo test --all-features --test integration -- single_thread
      
